// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwuAKYpYqM7fgfAOuEqF9Ui4c_QDz6_Yg',
    appId: '1:609979181365:web:460f3c6448ed25748fc47c',
    messagingSenderId: '609979181365',
    projectId: 'drone-kiralama',
    authDomain: 'drone-kiralama.firebaseapp.com',
    storageBucket: 'drone-kiralama.firebasestorage.app',
    measurementId: 'G-LK3K7CMEMY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-9Ysn_qr7uImC-Tfocblj9vS1_FW7cA8',
    appId: '1:609979181365:android:eea00c7224962b408fc47c',
    messagingSenderId: '609979181365',
    projectId: 'drone-kiralama',
    storageBucket: 'drone-kiralama.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaSd0R53V8CHkb5CTTMyb3-xo1-HkrAmk',
    appId: '1:609979181365:ios:11d24a9c29ba96fa8fc47c',
    messagingSenderId: '609979181365',
    projectId: 'drone-kiralama',
    storageBucket: 'drone-kiralama.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaSd0R53V8CHkb5CTTMyb3-xo1-HkrAmk',
    appId: '1:609979181365:ios:11d24a9c29ba96fa8fc47c',
    messagingSenderId: '609979181365',
    projectId: 'drone-kiralama',
    storageBucket: 'drone-kiralama.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwuAKYpYqM7fgfAOuEqF9Ui4c_QDz6_Yg',
    appId: '1:609979181365:web:a2095f8745837cd98fc47c',
    messagingSenderId: '609979181365',
    projectId: 'drone-kiralama',
    authDomain: 'drone-kiralama.firebaseapp.com',
    storageBucket: 'drone-kiralama.firebasestorage.app',
    measurementId: 'G-9NYG3TF4C4',
  );
}
